# Generated by Django 5.2.17 on 2026-09-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='discogs_enriched',
            field=models.BooleanField(default=False),
        ),
    ]
