# Generated by Django 5.2.17 on 2026-09-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_album_discogs_enriched'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='similar_artists',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='artist',
            name='top_albums',
            field=models.JSONField(default=list),
        ),
    ]
