# Generated by Django 5.2.17 on 2026-09-06 23:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_artist_similar_artists_artist_top_albums'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seed_artists', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('found', 'found'), ('exhausted', 'exhausted'), ('failed', 'failed')], default='pending', max_length=20)),
                ('visited_per_seed', models.JSONField(default=dict)),
                ('frontier_per_seed', models.JSONField(default=dict)),
                ('came_from', models.JSONField(default=dict)),
                ('bridge_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('current_depth', models.IntegerField(default=0)),
                ('max_depth', models.IntegerField(default=6)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
