# Generated by Django 5.2.17 on 2026-09-13 02:37

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_connectionsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsearch',
            name='node_limit',
            field=models.IntegerField(default=catalog.models._default_node_limit),
        ),
        migrations.AddField(
            model_name='connectionsearch',
            name='stopped_reason',
            field=models.CharField(blank=True, choices=[('', 'none'), ('node_limit', 'node_limit')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='connectionsearch',
            name='total_discovered',
            field=models.IntegerField(default=0),
        ),
    ]
