# Generated by Django 5.2.17 on 2026-09-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_connectionsearch_node_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='discogs_enriched',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='album',
            name='styles',
        ),
    ]
