# Generated by Django 5.2.17 on 2026-09-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_album_genres_styles_discogs_enriched'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsearch',
            name='payload_revision',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='connectionsearch',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('paused', 'paused'), ('found', 'found'), ('exhausted', 'exhausted'), ('failed', 'failed'), ('stopped', 'stopped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='connectionsearch',
            name='stopped_reason',
            field=models.CharField(blank=True, choices=[('', 'none'), ('node_limit', 'node_limit'), ('user_stop', 'user_stop')], default='', max_length=30),
        ),
    ]
